### ISSUE TITLE
Suggested improvement on shouldComponentUpdate

### ISSUE THREAD

**Issue by cwelch5** [gaearon/react-side-effect#11]
If I have a component that I am passing into SideEffect that has an API as follows:

```
<Component
     data={[
          {key: "value"},
          {key: "value"}
     ]}
/>
```

The problem is that when an array of objects is passed in as a prop, SideEffect will do a shallow compare that will always consider these props different because React considers this to be a new array and objects created.  Would you consider doing a deep equal compare in shouldComponentUpdate in order to prevent unnecessary renders and emitChange calls?

We found deep-equal (https://github.com/substack/node-deep-equal) is a good library.

Thanks for your consideration.

**Comment by gaearon** [comment]
Deep equality comparison is potentially expensive.
If you need it, you may wrap the result component into another component with a stricter check.
