### ISSUE TITLE
Can’t find instance of wrapped side-effect component with react test utils

### ISSUE THREAD

**Issue by lo1tuma** [gaearon/react-side-effect#12]
I’ve tried to update to `react-side-effect` 1.0.1 today, but my tests are failing.

I have a component `MetaDescription` which is wrapped using the `withSideEffect` function.
In my test I render the `Application` component which renders `MetaDescription`.

``` js
var application = TestUtils.renderIntoDocument(<Application />);
var description = TestUtils.findRenderedComponentWithType(application, MetaDescription);

expect(description).to.have.deep.property('props.description', 'foo bar');
```

`findRenderedComponentWithType` fails, because it can’t find an instance of `MetaDescription`:

```
    Error: Did not find exactly one match for componentType:function SideEffect() {
      Component.apply(this, arguments);
    }
```

I’ve change `react-side-effect` locally to use `React.createClass` instead of only calling `Component.apply(this, arguments);` in the constructor, and everything worked again.

**Comment by gaearon** [comment]
We can either do that, or set up prototype chain properly (I think that's what confuses TestUtils).

I'd accept a PR that adds a Babel build step like in [library-boilerplate](https://github.com/gaearon/library-boilerplate) and uses proper `class SideEffect extends Component` syntax. Then it would work.

**Comment by lo1tuma** [comment]
Yikes, I didn’t mean to close this issue with the reference in #13.

**Comment by gaearon** [comment]
Whoopsie.
