### ISSUE TITLE
Warning with React 0.14.0-rc1

### ISSUE THREAD

**Issue by jackmoore** [gaearon/react-side-effect#16]
Getting the following console warning when using react-document-title v2.0.0 and react-side-effect v1.0.1:

```
SideEffect(Component)(...): React component classes must extend React.Component.
```

**Comment by cesarandreu** [comment]
+1 It's giving me a warning with react-helmet as well.

**Comment by xpepermint** [comment]
+1

**Comment by gaearon** [comment]
Fixed in 1.0.2.

**Comment by Sridatta7** [comment]
Am I the only one facing this warning in 1.0.2 as well?

**Comment by cesarandreu** [comment]
Thanks!
