### ISSUE TITLE
Is server side rendering safe?

### ISSUE THREAD

**Issue by ondrejbartas** [gaearon/react-side-effect#18]
Hi I would like to ask you.

How do you ensure that server side rendering will not mismatch in concurrent requests?

**Comment by mars** [comment]
The server-side render [`ReactDOMServer.renderToString( … )`](https://facebook.github.io/react/docs/top-level-api.html#reactdomserver.rendertostring) call is synchronous, so it seems there is no need for server-side, async-safeness within React Side Effect.

But it's possible to write code using React Side Effect that will leak memory on the server. [React Document Title solves this with a `rewind()`](https://github.com/gaearon/react-document-title#server-usage) call to clean-up after each server-side render.

Along these lines, the call to clean-up must not occur in a callback, promise, or after awaits.

``` javascript
const html = ReactDOMServer.renderToString( … );
/*
    ^^^^^
    No async code before the clean-up.
    vvvvv
*/
const title = DocumentTitle.rewind();
```

**Comment by gaearon** [comment]
@mars, thank you for explaining!

**Comment by gaearon** [comment]
See also https://github.com/gaearon/react-document-title/issues/7#issuecomment-68914797.
