### ISSUE TITLE
Update shallowequal dependency

### ISSUE THREAD

**Issue by gajus** [gaearon/react-side-effect#35]
@dashed just released a v1 of https://github.com/dashed/shallowequal which (among other improvements) removes the dependency on lodash.

Despite being a major version update, it does not have breaking API changes. Therefore, an update simply requires to bump the version in package.json and release a patch.

**Comment by lourd** [comment]
Cool cool. Just published v1.1.1 with a v1.0.0 shallowequal version dependency
