### ISSUE TITLE
Breaking webpack production builds using shallowequal@1.0.0

### ISSUE THREAD

**Issue by gimdongwoo** [gaearon/react-side-effect#36]
https://github.com/dashed/shallowequal/issues/8

**Comment by whymarrh** [comment]
To clarify the issue, `shallowequal@1.0.0` breaks a few folks' webpack builds as it uses ES6 `let`.

@lourd would you be interested in reverting b339b38cccb0d89a6a15e5dc32574e34d8124f63 (or a PR that does so)?

**Comment by lourd** [comment]
Yup, I'll publish v1.1.2 now that reverts the commit.

**Comment by whymarrh** [comment]
Thanks, I can confirm that everything works

**Comment by daybreaker** [comment]
@lourd About how long does this take to get caught by other packages using this as a dependency?

We're using one that had "react-side-effect": "^1.1.0" and even though it grabbed 1.1.1 and broke our build, it isnt grabbing 1.1.2

Has it been officially "released" yet?

**Comment by lourd** [comment]
It's officially released, yes. You can see the published versions using the yarn or npm clients, which pull from the npm registry.

```sh
(yarn|npm) info react-side-effect
```

Your version resolution is dependent on which package manager client you're using, and any possible caching going on in your environment.

**Comment by daybreaker** [comment]
Thanks for the reply!
