### ISSUE TITLE
Refactored as ES6 class and High-order Component

### ISSUE THREAD

**Issue by cwelch5** [gaearon/react-side-effect#4]
I refactored react-side-effect as an ES6 class to be used as a high-order component instead of a mixin.  Would you be interested in seeing it, I can submit a PR?

**Comment by gaearon** [comment]
Sure, please do.

**Comment by BradEstey** [comment]
👍 +1

**Comment by mikestopcontinues** [comment]
+1

**Comment by gaearon** [comment]
Done in 1.0.0.
