### ISSUE TITLE
question - why `rewind` is not supported at client side?

### ISSUE THREAD

**Issue by liweinan0423** [gaearon/react-side-effect#43]
I am currently working with Apollo GraphQL and I want to do some sort of `prefetch` before transiting to a new route at client side. This would need to walk through the whole component tree to fetch data before the actual rendering happens. But in my component tree, there are some component produces side effect where I have to do `rewind` after going through the component tree. But the `rewind` method is only callable at server side.

I am wondering the reason of this nature

**Comment by lourd** [comment]
`rewind` doesn't "rewind" in an undo sense. It gets the value of the side effect state and then clears it internally.

For your case, I think you could achieve your needs through the function you pass for `handleStateChangeOnClient`. Have some boolean variable that represents whether you want to handle side effects or not, and handle the state change differently if you are or aren't.

That's non-trivial to do for component's you didn't write... you may to do the same thing through a wrapper component using the standard prop-change hooks.
