### ISSUE TITLE
How about this

### ISSUE THREAD

**Issue by jituanlin** [gaearon/react-side-effect#50]
Manage stateful data is painful, but with some functional pattern math power, we can do it simply,
See [this](https://jituanlin.github.io/frontend/Bind-API-In_React-one-line.html)
For now, It just bind API for stateful data, but I will implement it for Redux.

**Comment by lourd** [comment]
Hi @jituanlin, thanks for sharing your article 🙂

The issue tracker is intended for bug reports, feature requests, and other library-specific discussion. I encourage you to share the article on other channels where it will have a better chance at attracting attention
