### ISSUE TITLE
Replace `UNSAFE_componentWillMount` with `constructor`

### ISSUE THREAD

**Issue by voodoocreation** [gaearon/react-side-effect#62]
This could be remedied by replacing `UNSAFE_componentWillMount` with a `constructor` definition, as that is the modern equivalent of using the now-deprecated `componentWillMount`. It will also avoid limiting your supported versions of `react`, as it's both backwards and forwards compatible.

https://github.com/gaearon/react-side-effect/blob/f1e020719f5cc429b96b260cab80ed51b63421a5/src/index.js#L70

**Comment by sabarasaba** [comment]
any chance we can get this merged in @gaearon ? this package is heavily used by `react-helmet` and im sure im not the only one bugged by all the warnings it generates :cat:

**Comment by andreyluiz** [comment]
@sabarasaba, there is https://github.com/iest/react-body-classname which is potentially impacted by this too.

**Comment by sophiebits** [comment]
Renaming to constructor isn't the correct fix as it won't be properly compatible with concurrent mode, where the render phase (including the constructor) might be called more than once.

**Comment by gaearon** [comment]
Like Sophie says, this isn't the right fix. https://github.com/gaearon/react-side-effect/pull/63#issuecomment-577149849
