### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by itsmepetrov** [gaearon/react-side-effect#7]
Since 0.14 version, React does not contain 'react/lib/invariant' and 'react/lib/shallowEqual' files. Now these files are available in [facebook/fbjs](https://github.com/facebook/fbjs)  repository.

**Comment by mikestopcontinues** [comment]
These effects are easy enough to write in vanilla js. I'd be happy to create a PR to that effect, @gaearon, if you're on board with the strategy.

**Comment by romanenko** [comment]
I think, this issue can be closed — #8 fixes it.
